version: "3"

services:
  contact-web:
    build:
      context: ../contact-web
    image: contact-web
    restart: on-failure
    environment:
      NODE_ENV: dev
      ENV: local
      PORT: 3001
    env_file:
      - ../contact-web/.env
    ports:
      - "3001:3001"
    command: sh -c "node index.js"

  alert-web:
    build:
      context: ../alert-web
    image: alert-web
    restart: on-failure
    environment:
      NODE_ENV: dev
      ENV: local
      PORT: 3000
    env_file:
      - ../alert-web/.env
    ports:
      - "3000:3000"
    command: sh -c "node index.js"

  notification-api:
    build:
      context: ../notification-api
    image: notification-api
    restart: on-failure
    environment:
      NODE_ENV: dev
      ENV: local
      PORT: 3002
    env_file:
      - ../notification-api/.env
    ports:
      - "3002:3002"
    command: sh -c "node index.js"
