version: "3"

services:
  contact-web:
    ports:
      - "9227:9229"
    volumes:
      - ../contact-web:/usr/src/app
    command: sh -c "wait-on tcp:db:5432 && nodemon --inspect=0.0.0.0 index.js"

  contact-api:
    ports:
      - "9231:9229"
    volumes:
      - ../contact-api:/usr/src/app
    command: sh -c "wait-on tcp:db:5432 && nodemon --inspect=0.0.0.0 index.js"

  # alert-web:
  #   ports:
  #     - "9228:9229"
  #   volumes:
  #     - ../alert-web:/usr/src/app
  #   command: sh -c "wait-on tcp:message-broker:5672 && wait-on tcp:db:5432 && nodemon --inspect=0.0.0.0 index.js"

  # notification-api:
  #   ports:
  #     - "9229:9229"
  #   volumes:
  #     - ../notification-api:/usr/src/app
  #   command: sh -c "wait-on tcp:message-broker:5672 && wait-on tcp:db:5432 && nodemon --inspect=0.0.0.0 index.js"

  # area-api:
  #   ports:
  #     - "9230:9229"
  #   volumes:
  #     - ../area-api:/usr/src/app
  #   command: sh -c "wait-on tcp:db:5432 && nodemon --inspect=0.0.0.0 index.js"
