version: "3"

services:
  contact-web:
    build:
      context: ../flood-xws-contact-web
    image: contact-web
    depends_on:
      - contact-rest-api
      - contact-api
      - area-api
      - db
    restart: on-failure
    environment:
      NODE_ENV: dev
      ENV: local
      PORT: 3001
      HOST: 0.0.0.0
      AREA_URL: "http://area-api:3004/areas"
      SUBSCRIPTION_PATCH_URL: "http://contact-rest-api:3000/subscription?id=eq.$${subscriptionId}"
      SUBSCRIPTION_POST_URL: "http://contact-api:3003/subscriptions"
      SUBSCRIPTION_GET_URL: "http://contact-rest-api:3000/subscription?id=eq.$${subscriptionId}"
      SUBSCRIPTION_DELETE_URL: "http://contact-rest-api:3000/subscription?id=eq.$${subscriptionId}"
      CONTACT_SUBSCRIPTION_GET_URL: "http://contact-rest-api:3000/contact?select=*,subscription(*,area(*))&id=eq.$${contactId}"
      CONTACT_GET_URL: "http://contact-rest-api:3000/contact?value=eq.$${value}"
      CONTACT_POST_URL: "http://contact-rest-api:3000/contact"
    env_file:
      - ../flood-xws-contact-web/.env
    ports:
      - "3001:3001"
    command: sh -c "node index.js"

  area-api:
    build:
      context: ../flood-xws-area-api
    image: area-api
    depends_on:
      - db
    restart: on-failure
    environment:
      NODE_ENV: dev
      ENV: local
      PORT: 3004
      HOST: 0.0.0.0
      DATABASE_URL: "postgres://postgres:postgres@db:5432"
    env_file:
      - ../flood-xws-area-api/.env
    ports:
      - "3004:3004"
    command: sh -c "wait-on tcp:db:5432 && node index.js"

  alert-web:
    build:
      context: ../flood-xws-alert-web
    image: alert-web
    depends_on:
      - db
    restart: on-failure
    environment:
      NODE_ENV: dev
      ENV: local
      PORT: 3000
      HOST: 0.0.0.0
      DATABASE_URL: "postgres://postgres:postgres@db:5432"
    env_file:
      - ../flood-xws-alert-web/.env
    ports:
      - "3000:3000"
    command: sh -c "wait-on tcp:db:5432 && node index.js"

  contact-api:
    build:
      context: ../flood-xws-contact-api
    image: contact-api
    depends_on:
      - db
      - contact-rest-api
    restart: on-failure
    environment:
      NODE_ENV: dev
      ENV: local
      PORT: 3003
      HOST: 0.0.0.0
      CONTACT_GET_URL: "http://contact-rest-api:3000/contact?id=eq.$${contactId}"
      SUBSCRIPTION_POST_URL: "http://contact-rest-api:3000/subscription"
    env_file:
      - ../flood-xws-contact-api/.env
    ports:
      - "3003:3003"
    command: sh -c "wait-on tcp:db:5432 && node index.js"

  swagger:
    image: swaggerapi/swagger-ui
    depends_on:
      - contact-rest-api
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: "http://localhost:3005"

  contact-rest-api:
    image: postgrest/postgrest
    ports:
      - "3005:3000"
    environment:
      PGRST_DB_URI:  "postgres://authenticator:authenticator@db:5432/postgres"
      PGRST_DB_SCHEMA: xws_rest
      PGRST_DB_ANON_ROLE: web_anon
    depends_on:
      - db

  db:
    build:
      context: ../flood-xws-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes: 
  pgdata:
