version: "3"

services:
  # contact-web:
  #   ports:
  #     - "9227:9229"
  #   volumes:
  #     - ../flood-xws-contact-web:/usr/src/app
  #   command: sh -c "nodemon --inspect-brk=0.0.0.0 index.js"

  alert-web:
    ports:
      - "9229:9229"
    volumes:
      - ../flood-xws-alert-web:/usr/src/app
    command: sh -c "nodemon --inspect=0.0.0.0 index.js"

  # area-api:
  #   ports:
  #     - "9230:9229"
  #   volumes:
  #     - ../area-api:/usr/src/app
  #   command: sh -c "wait-on tcp:db:5432 && nodemon --inspect=0.0.0.0 index.js"
